### ISSUE TITLE
19c

### ISSUE THREAD

**Issue by PedroPCardoso** [sea84/Debezium-oracle#1]
Does this code work on version 19c? How to fix this error?

 [io.debezium.connector.oracle.OracleConnector]
java.lang.RuntimeException: Failed to resolve Oracle database version
	at io.debezium.connector.oracle.OracleConnection.resolveOracleDatabaseVersion(OracleConnection.java:158)
	at io.debezium.connector.oracle.OracleConnection.<init>(OracleConnection.java:70)
	at io.debezium.connector.oracle.OracleConnector.validateConnection(OracleConnector.java:74)
	at io.debezium.connector.common.RelationalBaseSourceConnector.validate(RelationalBaseSourceConnector.java:52)

my register logminer:

{
  "name": "inventory-connector72",

  "config": {
    "connector.class": "io.debezium.connector.oracle.OracleConnector",

    "tasks.max": "1",
     
    
    "database.server.name": "server4",

    "database.user": "c##debezium",

    "database.password": "dbz",

    "database.url": "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=OFF)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=SERVICE_NAME=)(SERVER=DEDICATED)))",

    "database.dbname": "ORCLCDB",
    
    "database.pdb.name": "ORCLPDB1",
    
    "database.history.kafka.bootstrap.servers": "kafka:9092",

    "database.history.kafka.topic": "schema-changes.inventory"
  }
}

**Comment by kekcment** [comment]
Yes, this very good question...
